config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'home#index'
  resources :courses do
    get 'assign_student', on: :member
    get 'grade_student', on: :member
    post 'assign_student_grade', on: :collection
    post 'assign_student_to_course', on: :collection
    get 'students', on: :member
  end
  resources :students do
    get 'grades', on: :member
    get 'courses', on: :member
    get 'dashboard', on: :collection
  end
  # get 'student/dashboard', to: 'students#dashboard', as: 'student_dashboard'
  #get 'admin/dashboard', to: 'admin#dashboard', as: 'admin_dashboard'
  #get 'admin/new_user', to: 'admin#new_user', as: :new_user_admin
  #get 'admin/students', to: 'admin#students', as: :admin_students
  #post 'admin/users', to: 'admin#create_user', as: :admin_users
  scope '/admin' do
    get 'dashboard', to: 'admin#dashboard', as: 'admin_dashboard'
    get 'new_user', to: 'admin#new_user', as: :new_user_admin
    post 'users', to: 'admin#create_user', as: :admin_users
    get 'students', to: 'admin#students', as: :admin_students
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :student_courses
  has_many :courses, through: :student_courses

  def self.search(search_param)
    search_param ? where("first_name LIKE ?", "%#{search_param}%") : none
  end

  def full_name
    first_name + ' ' + last_name
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy grades courses ]
  before_action :authenticate_user!
  before_action :check_admin, only: [:index, :destroy]

  def index
    @students = Student.all
  end

  def dashboard
    redirect_to edit_student_path(current_user.student) if current_user.student.first_name.blank?
    @student = current_user.student
    @courses = current_user.student.courses
  end

  def show; end

  def search
    @students = Student.search(params[:search])
  end

  def courses
  end

  def grades
    @student_courses = @student.student_courses
  end

  def new
    @student = Student.new
  end

  def edit; end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student, notice: "Student was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @student.update(student_params)
      if current_user.student?
        redirect_to dashboard_students_path, notice: "Profile updated successfully."
      else
        redirect_to @student, notice: "Student updated successfully."
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @student.destroy!

    redirect_to students_url, notice: "Student was successfully destroyed."
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:first_name, :last_name)
    end

    def check_admin
      redirect_to root_path, alert: "Unauthorized access!" unless current_user.admin?
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>

    <%= form.label :last_name %>
    <%= form.text_field :last_name %>

    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
<p>
    <strong>Name:</strong>
    <%= student.first_name %>
  </p>

  <p>
    <strong>Last Name:</strong>
    <%= student.last_name %>
  </p>

</div>

app/views/students/courses.html.erb
<h1><%= @student.first_name %> Courses List</h1>

<% @student.courses.each do |course| %>
  <p><%= course.name %></p>
  <p><%= course.year %></p>
<% end %>

<%= link_to "Back", dashboard_students_path %>

app/views/students/dashboard.html.erb
<h1>Student Dashboard</h1>
<p>Welcome <%=@student.full_name%>!</p>
<%= link_to "My courses", courses_student_path(current_user.student) %>
<%= link_to "My grades", grades_student_path(current_user.student) %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/grades.html.erb
<h1>Grades</h1>

<% @student_courses.each do |st| %>
  <h2>Course: <%= st.course.name %></h2>
  <table>
    <thead>
      <tr>
        <th>Score</th>
        <th>Quarter</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% st.grades.each do |grade| %>
        <tr>
          <td><%= grade.score %></td>
          <td><%= grade.quarter %></td>
          <td><%= grade.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <ul class="list-group">
  <% @students.each do |student| %>
    <li class="list-group-item">
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
    </li>
  <% end %>
  </ul>
</div>

<%= link_to "New student", new_user_admin_path, class: 'btn btn-primary mt-4' %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card ms-auto me-auto " style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%=@student.full_name%></h5>
    <%= link_to "Edit this student", edit_student_path(@student), class: 'd-block' %>
    <%= link_to 'View Grades', grades_student_path(@student), class: 'd-block' %>
    <%= link_to "Back to students", students_path, class: 'd-block' %>

  <%= button_to "Destroy this student", @student, method: :delete, class: 'btn btn-danger mt-1' %>
  </div>
</div>