config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'home#index'
  resources :courses do
    get 'assign_student', on: :member
    get 'grade_student', on: :member
    post 'assign_student_grade', on: :collection
    post 'assign_student_to_course', on: :collection
    get 'students', on: :member
  end
  resources :students do
    get 'grades', on: :member
    get 'courses', on: :member
    get 'dashboard', on: :collection
  end
  # get 'student/dashboard', to: 'students#dashboard', as: 'student_dashboard'
  #get 'admin/dashboard', to: 'admin#dashboard', as: 'admin_dashboard'
  #get 'admin/new_user', to: 'admin#new_user', as: :new_user_admin
  #get 'admin/students', to: 'admin#students', as: :admin_students
  #post 'admin/users', to: 'admin#create_user', as: :admin_users
  scope '/admin' do
    get 'dashboard', to: 'admin#dashboard', as: 'admin_dashboard'
    get 'new_user', to: 'admin#new_user', as: :new_user_admin
    post 'users', to: 'admin#create_user', as: :admin_users
    get 'students', to: 'admin#students', as: :admin_students
  end
end

app/views/admin/_student_admin.html.erb
<h1>asd</h1>

app/views/admin/dashboard.html.erb
    <h2 class="pb-2 border-bottom">Admin Dashboard</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
      <div class="feature col">
        <h3 class="fs-2">Create new user</h3>
        <p>Create a new user and assign it a role.</p>
        <%= link_to "New user", new_user_admin_path %>
      </div>
      <div class="feature col">
        <h3 class="fs-2">Students List</h3>
        <p>Check all the registered students in the system</p>
        <%= link_to "List of Students", students_path %>
      </div>
      <div class="feature col">
        <h3 class="fs-2">Courses List</h3>
        <p>View all created courses in the system.</p>
        <%= link_to "List of Courses", courses_path %>
      </div>
    </div>

app/views/admin/new_user.html.erb
<%= form_for(@user, url: admin_users_path, html: { class: 'form-horizontal' }) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= fields_for :student do |student_form| %>
    <div class="field">
      <%= student_form.label :first_name, class: 'control-label' %>
      <%= student_form.text_field :first_name, autofocus: true, class: 'form-control' %>
    </div>

    <div class="field">
      <%= student_form.label :last_name, class: 'control-label' %>
      <%= student_form.text_field :last_name, autofocus: true, class: 'form-control' %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email, class: 'control-label' %>
    <%= f.email_field :email, autofocus: true, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :password, class: 'control-label' %>
    <%= f.password_field :password, autocomplete: 'new-password', class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, class: 'control-label' %>
    <%= f.password_field :password_confirmation, autocomplete: 'new-password', class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :role, class: 'control-label' %>
    <%= f.select :role, User.roles.keys.map { |role| [role.titleize, role] }, {}, { class: 'form-control' } %>
  </div>

  <div class="actions mt-4">
    <%= f.submit 'Create User', class: 'btn btn-primary' %>
    <%= link_to "Cancel", admin_dashboard_path, class: 'btn btn-danger' %>
  </div>

<% end %>

app/views/admin/students.html.erb
<h1>Student list</h1>

<div id="students">
  <ul class="list-group">
  <li class="list-group-item">An item</li>
  <% @students.each do |student| %>
    <li class="list-group-item">
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
    </li>
  <% end %>
  </ul>
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>