config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'home#index'
  resources :courses do
    get 'assign_student', on: :member
    get 'grade_student', on: :member
    post 'assign_student_grade', on: :collection
    post 'assign_student_to_course', on: :collection
    get 'students', on: :member
  end
  resources :students do
    get 'grades', on: :member
    get 'courses', on: :member
    get 'dashboard', on: :collection
  end
  # get 'student/dashboard', to: 'students#dashboard', as: 'student_dashboard'
  #get 'admin/dashboard', to: 'admin#dashboard', as: 'admin_dashboard'
  #get 'admin/new_user', to: 'admin#new_user', as: :new_user_admin
  #get 'admin/students', to: 'admin#students', as: :admin_students
  #post 'admin/users', to: 'admin#create_user', as: :admin_users
  scope '/admin' do
    get 'dashboard', to: 'admin#dashboard', as: 'admin_dashboard'
    get 'new_user', to: 'admin#new_user', as: :new_user_admin
    post 'users', to: 'admin#create_user', as: :admin_users
    get 'students', to: 'admin#students', as: :admin_students
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy assign_student students grade_student ]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def assign_student
    @searched_students = Student.search(params[:search])
  end

  def students
  end

  def grade_student
    @course = Course.find(params[:course_id])
    @student = Student.find(params[:student_id])
    @grade = Grade.new
  end

  def assign_student_grade
    @course = Course.find(params[:grade][:course_id])
    @student = Student.find(params[:grade][:student_id])
    @student_course = @student.student_courses.where(course_id: @course.id).first
    @grade = @student_course.grades.new(grade_params)

    if @grade.save
      redirect_to @course, notice: 'Grade assigned successfully.'
    else
      render :grade_student
    end
  end
  def assign_student_to_course
    @course = Course.find(params[:course_id])
    student = Student.find(params[:student_id])
    if @course.students.include?(student)
      redirect_to course_path(@course), notice: "cannot add student, #{student.first_name} is already assigned to the course."
    else
      @course.students << student
      redirect_to course_path(@course), notice: "#{student.first_name} assigned to the course successfully."
    end
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course, notice: "Course was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @course.update(course_params)
      redirect_to @course, notice: "Course updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @course.destroy!

    redirect_to courses_url, notice: "Course was successfully destroyed."
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :year)
    end

    def grade_params
      params.require(:grade).permit(:score, :quarter)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Name:</strong>
    <%= course.name %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= course.year %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.text_field :year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/assign_student.html.erb
<h1>Assign Student to <%= @course.name %></h1>

<%= form_with(url: assign_student_course_path, method: :get) do |form| %>
  <%= form.text_field :search, placeholder: "Search by student name" %>
  <%= form.submit "Search" %>
<% end %>

<ul>
  <% @searched_students.each do |student| %>
    <% unless student.nil? %>
      <li><%= link_to student.first_name, assign_student_to_course_courses_path(course_id: @course.id, student_id: student.id), data: { turbo_method: :post } %></li>
    <% end %>
  <% end %>
</ul>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/grade_student.html.erb
<h1>Grade <%= @student.first_name %> for <%= @course.name %>

<%= form_with(model: [@course, @student, @grade], url: assign_student_grade_courses_path, method: :post) do |form| %>
  <%= form.hidden_field :course_id, value: @course.id %>
  <%= form.hidden_field :student_id, value: @student.id %>
  <div>
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div>
    <%= form.label :quarter %>
    <%= form.select :quarter, Grade.quarters.keys %>
  </div>

  <%= form.submit %>
<% end %>

<%= link_to "Back to this course", @course %>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Courses</h1>

<div id="courses">
  <% @courses.each do |course| %>
    <%= render course %>
    <p>
      <%= link_to "Show this course", course %>
    </p>
  <% end %>
</div>

<%= link_to "New course", new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @course %>

<div>
  <%= link_to "Edit this course", edit_course_path(@course) %> |
  <%= link_to "Students in this course", students_course_path(@course) %> |
  <%= link_to "Assign a student to this course", assign_student_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>

  <%= button_to "Destroy this course", @course, method: :delete %>
</div>

app/views/courses/students.html.erb
<h1>Students list for <%= @course.name %></h1>

<div id="courses_students">
  <ul>
    <% @course.students.each do |student| %>
      <% unless student.nil? %>
        <li><%=student.first_name + ' ' + student.last_name%> <%= link_to "Grade", grade_student_course_path(course_id: @course, student_id: student) %></li>
      <% end %>
    <% end %>
  </ul>
</div>

<%= link_to "Back to this course", @course %>